### ISSUE TITLE
Run Local Test issue

### ISSUE THREAD

**Issue by endyranaudo** [learn-co-curriculum/js-rails-as-api-pokemon-teams-project#2]
Learn is not available in this lab, hence I cannot run any local test

**Comment by rrcobb** [comment]
There are no tests for this lab - it's behavior driven, so you'll have to test it yourself in the browser to tell that you have completed it successfully. 

We should add some clarification to the Readme so that it's clear how you should test your code.

**Comment by maxwellbenton** [comment]
Hi @endyranaudo,

Thank you for opening this issue and providing feedback. This lesson does not contain any tests, but we have added an additional note indicating this in the readme so other students will be aware of this.

Thank you for contributing to a learn.co lesson!
