### ISSUE TITLE
"Completed Example" video broken in student repo - Content Exceeded

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/js-rails-as-api-pokemon-teams-project#2]
In learn.co and in github itself.

<img width="562" alt="Screen Shot 2020-04-20 at 5 58 17 PM" src="https://user-images.githubusercontent.com/12770108/79803726-8a4a1080-8330-11ea-9959-3a6f3d218e70.png">

**Comment by Sdcrouse** [comment]
This seems to have been fixed, at least on my end.

**Comment by garettarrowood** [comment]
Yes -- I think this was during a Github outage and, in general, many of their assets were not rendering. Thank you for checking!
