### ISSUE TITLE
Rails backend initializes as a git repo

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/js-rails-as-api-pokemon-teams-project#3]
I believe 
```
rails new pokemon-teams-backend --api
```
should be replaced with
```
rails new pokemon-teams-backend --api --skip-git
```

I just had a few students attempt this lab and we were confused that the rails backend was not getting tracked in git. 

Then the `.gitignore` on root will need to be updated to not track ignorable files in the backend folder.

**Comment by lizbur10** [comment]
Hi there! Thanks for reporting this issue. A note has been added to the instructions letting students know they should delete the .git folder from the Rails project, so hopefully this won't be an issue in future.
