### ISSUE TITLE
Question about where to put cors-related code/this lab differs from the first introduction of it

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-rails-as-api-pokemon-teams-project#5]
This lab puts it in cors.rb. A few lessons back, similar code was put into config/application.rb. Possible to explain the difference, and why/how it matters/where it connects, or make it more consistent? Thanks for considering. 

Miriam

**Comment by maxwellbenton** [comment]
Hi @MiriamPeskowitz,

Thank you for pointing this out. We've added a note calling this difference out and explaining a bit - both methods work, but the `cors.rb` file is provided for the purpose. We will review the previous lessons to see if we can make things more consistent.
