### ISSUE TITLE
Consider including female names in trainer list 

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-rails-as-api-pokemon-teams-project#6]
Here's the list of Trainers in db/seeds.rb. Can you add/swap some out for some female names? Flatiron is known for its inclusivity in tech (and in pokemom training)! Thanks for considering. 

trainers_name = [
  'Prince',
  'Dick',
  'Garry',
  'Jason',
  'Matt',
  'Noah',
  'Adam',
  'Arthur'
]

**Comment by maxwellbenton** [comment]
Hi @MiriamPeskowitz,

We totally agree and have updated this list to include female names. Thank you for spotting this and providing feedback!

**Comment by MiriamPeskowitz** [comment]
You bet! Thanks for receiving it so graciously.



*Miriam Peskowitz, Ph.D.*

NY Times bestselling author, *The Daring Book for Girls*

Just published!!*  Code Like a Girl: Rad Tech Projects + Practical Tips
<https://www.amazon.com/Code-Like-Girl-Projects-Practical/dp/1524713899/ref=sr_1_1?crid=1SVCICPKYA7SF&keywords=code+like+a+girl+rad+tech+projects+and+practical+tips&qid=1567648048&s=gateway&sprefix=code+like+a+girl+%2Caps%2C124&sr=8-1>*
For anyone who's wanted to learn to code.

codelikeagirlbook.com   ||   mpeskowitz.com
